tests ig

diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -135,53 +135,120 @@ jobs:
           touch /srv/app/junit/result/test-summary.md
       - name: Check Source Dependency Versions
         run: |
+          cd /srv/app/src/ckanext-canada
+          BRANCH="${{ github.head_ref || github.ref_name }}"
+          git fetch origin
+          if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
+            git checkout "$BRANCH"
+          else
+            git checkout -b "$BRANCH" "origin/$BRANCH"
+          fi
+          git fetch
+          git pull --ff-only || true
+          CONFIG="/srv/app/src/ckanext-canada/.github/test-dependencies.json";
+          cd /srv/app;
           source /srv/app/venv/bin/activate
+          CURRENT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}";
           for dir in /srv/app/src/*; do
             srcName=$(echo "$dir" | awk -F'/' '{print $NF}');
             if [[ -d "$dir/.git"  ]]; then
+                DO_PIP_REINSTALL='false';
                 printf "\n${srcName}: Checking for updates..."
                 cd $dir;
-                current_branch=$(git rev-parse --abbrev-ref HEAD);
-                if [[ "$srcName" == "ckan" ]]; then
-                    git fetch canada;
-                    reslog=$(git log HEAD..canada/$current_branch --oneline);
+                if jq -e --arg name "$srcName" '.repositories | has($name)' "$CONFIG" > /dev/null; then
+                  printf "\n    ${srcName}: Checking configuration from ${CONFIG}..."
+                  current_branch=$(
+                    jq -r \
+                      --arg repo "$srcName" \
+                      --arg current "$CURRENT_BRANCH" \
+                      '
+                      .repositories[$repo].branches as $b
+                      | $b[$current]
+                        // (if $current | startswith("feature/") then $b["feature/*"] else null end)
+                        // (if $current | startswith("fix/") then $b["fix/*"] else null end)
+                        // $b["*"]
+                      ' \
+                      "$CONFIG"
+                    );
+                  printf "\n    ${srcName}: ${CURRENT_BRANCH} configured to use branch ${current_branch}...";
+                  DO_PIP_REINSTALL='true';
                 else
-                    git fetch origin;
-                    reslog=$(git log HEAD..origin/$current_branch --oneline);
+                  printf "\n    ${srcName}: Using default/current branch..."
+                  current_branch=$(git rev-parse --abbrev-ref HEAD);
+                  printf "\n    ${srcName}: using branch ${current_branch}...";
                 fi;
-                if [[ "${reslog}" == "" ]]; then
-                    printf "\n${srcName}: Up to date. Skipping..."
+                if [[ -z "$current_branch" || "$current_branch" == "null" ]]; then
+                  current_branch=$(git rev-parse --abbrev-ref HEAD);
+                  printf "\n    ${srcName}: unable to determine branch using current branch ${current_branch}..."
+                fi
+                if [[ "$srcName" == "ckan" ]]; then
+                  git fetch canada;
+                  if git show-ref --verify --quiet "refs/heads/$current_branch"; then
+                    git checkout "$current_branch"
+                  else
+                    git checkout -B "$current_branch" "canada/$current_branch"
+                  fi
+                  git fetch
+                  git pull --ff-only || true
+                  reslog=$(git log HEAD..canada/$current_branch --oneline);
                 else
-                    git pull || true;
-                    printf "\n${srcName}: Pulled updated code. Re-initializing in python environment..."
-                    cd /srv/app;
-                    if [[ -f "$dir/requirements.txt" ]]; then
-                        pip install -r $dir/requirements.txt || true;
-                    fi;
-                    if [[ -f "$dir/dev-requirements.txt" ]]; then
-                        pip install -r $dir/dev-requirements.txt || true;
-                    fi;
-                    if [[ -f "$dir/test-requirements.txt" ]]; then
-                        pip install -r $dir/test-requirements.txt || true;
-                    fi;
-                    if [[ -f "$dir/setup.py" ]]; then
-                        python $dir/setup.py develop || true;
-                    fi;
+                  git fetch origin;
+                  if git show-ref --verify --quiet "refs/heads/$current_branch"; then
+                    git checkout "$current_branch"
+                  else
+                    git checkout -B "$current_branch" "origin/$current_branch"
+                  fi
+                  git fetch
+                  git pull --ff-only || true
+                  reslog=$(git log HEAD..origin/$current_branch --oneline);
+                fi;
+                printf "\n    ${srcName}: git info\n";
+                printf "\n";
+                git branch --show-current;
+                printf "\n";
+                git rev-parse HEAD;
+                printf "\n";
+                git log -1 --oneline;
+                printf "\n";
+                printf "\n    ${srcName}: pip info\n";
+                pip show ${srcName};
+                if [[ "${reslog}" == "" && "${DO_PIP_REINSTALL}" == "false" ]]; then
+                  printf "${srcName}: Up to date. Skipping..."
+                else
+                  git pull --ff-only || true;
+                  printf "\n${srcName}: Pulled updated code. Re-initializing in python environment..."
+                  cd /srv/app;
+                  if [[ -f "$dir/requirements.txt" ]]; then
+                    pip install -r $dir/requirements.txt || true;
+                  fi;
+                  if [[ -f "$dir/dev-requirements.txt" ]]; then
+                    pip install -r $dir/dev-requirements.txt || true;
+                  fi;
+                  if [[ -f "$dir/test-requirements.txt" ]]; then
+                    pip install -r $dir/test-requirements.txt || true;
+                  fi;
+                  if [[ -f "$dir/setup.py" ]]; then
+                    python $dir/setup.py develop || true;
+                  fi;
                 fi;
             else
                 printf "\n${srcName}: Not a source repository. Skipping..."
             fi;
+            printf "\n\n";
           done;
           cd /srv/app;
       - name: Checkout Repository (${{ github.head_ref || github.ref_name }})
         run: |
           cd /srv/app/src/ckanext-canada
+          BRANCH="${{ github.head_ref || github.ref_name }}"
           git fetch origin
-          if [[ "${{ github.head_ref || github.ref_name }}" != "master" ]]; then
-            git checkout -b ${{ github.head_ref || github.ref_name }} origin/${{ github.head_ref || github.ref_name }}
-          fi;
+          if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
+            git checkout "$BRANCH"
+          else
+            git checkout -b "$BRANCH" "origin/$BRANCH"
+          fi
           git fetch
-          git pull
+          git pull --ff-only || true
           source /srv/app/venv/bin/activate
           pip install -e .
           pip install -r requirements.txt
@@ -196,13 +263,16 @@ jobs:
       - name: Setup Databases
         run: |
           source /srv/app/venv/bin/activate
-          . /srv/app/src/ckanext-canada/links/ckan/bin/postgres_init/1_create_ckan_db.sh
-          . /srv/app/src/ckanext-canada/links/ckan/bin/postgres_init/2_create_ckan_datastore_db.sh
+          . /srv/app/src/ckan/bin/postgres_init/1_create_ckan_db.sh
+          . /srv/app/src/ckan/bin/postgres_init/2_create_ckan_datastore_db.sh
           ckan -c /srv/app/src/ckanext-canada/test-core.ini db init
           ckan -c /srv/app/src/ckanext-canada/test-core.ini datastore set-permissions | psql -U postgres --set ON_ERROR_STOP=1
+          ckan -c /srv/app/src/ckanext-canada/test-core.ini validation init-db
+          ckan -c /srv/app/src/ckanext-canada/test-core.ini security migrate
           ckan -c /srv/app/src/ckanext-canada/test-core.ini canada update-triggers
           ckan -c /srv/app/src/ckanext-canada/test-core.ini recombinant create-triggers -a
           ckan -c /srv/app/src/ckanext-canada/test-core.ini db upgrade
+          ckan -c /srv/app/src/ckanext-canada/test-core.ini db pending-migrations --apply
           ckan -c /srv/app/src/ckanext-canada/test-core.ini db pending-migrations --apply
       - name: Download Test Durations
         if: needs.define-matrix.outputs.restored == 'true'
@@ -326,7 +396,7 @@ jobs:
                 if [[ "${reslog}" == "" ]]; then
                     printf "\n${srcName}: Up to date. Skipping..."
                 else
-                    git pull || true;
+                    git pull --ff-only || true;
                     printf "\n${srcName}: Pulled updated code. Re-initializing in python environment..."
                     cd /srv/app;
                     if [[ -f "$dir/requirements.txt" ]]; then
@@ -355,7 +425,7 @@ jobs:
             git checkout -b ${{ github.head_ref || github.ref_name }} origin/${{ github.head_ref || github.ref_name }}
           fi;
           git fetch
-          git pull
+          git pull --ff-only || true
           source /srv/app/venv/bin/activate
           pip install -e .
           pip install -r requirements.txt
